"""New fields in user model

Revision ID: 0c5d2c1ccae1
Revises: 4eafb6cab524
Create Date: 2018-08-18 22:20:44.199012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5d2c1ccae1'
down_revision = '4eafb6cab524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('datetime_joined', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('datetime_last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'datetime_last_seen')
    op.drop_column('user', 'datetime_joined')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
